### PR TITLE
adding required pipy fields

### PR DESCRIPTION
**Pull request by JulianNorton**

### CODE REVIEW

**Comment by JulianNorton** [comment]
The only thing I think is missing is `entry_points`. Not sure if this should be `bomb` or something else?

https://packaging.python.org/tutorials/distributing-packages/#entry-points

**Comment by MartinHarding** [comment]
@JulianNorton 
- removed `inflect` because it's only used in the cli-example, and we'll add it if/when we merge that branch
- removed `random` because it's a built in module and those don't need to be listed (I think?)
- fixed keywords (space delimited, not comma delimited)
- changed topic to Puzzle Games (just 'cause)
- changed intended audience to Developers (classifiers are supposed to map to one of https://pypi.python.org/pypi?%3Aaction=list_classifiers)
- added you as an author, if you're okay with that
- changed version to 0.0.0 and the stage to planning (will set it to 0.0.1 and alpha or such when submitted to PyPi)

I'm not really sure about the entry points yet.

**Comment by MartinHarding** [comment]
Oh, also fixed an import bug—the https://github.com/pypa/sampleproject/blob/master/setup.py example uses find_packages from setup tools, but it hadn't been imported in your original changes

**Comment by JulianNorton** [comment]
Random has to be imported
```
>>> random.randint(0,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'random' is not defined
>>> import random
>>> random.randint(0,1)
1
>>>
```

**Comment by MartinHarding** [comment]
@JulianNorton sorry, I meant standard modules not built in (which implies language functions) — you should not list standard modules in install_requires: https://stackoverflow.com/questions/40730660/is-there-any-reason-to-list-standard-library-dependencies-when-using-setuptools

**Pull request merged**
